/**
 * Dictionary entries for category: agricultura
 * Generated by scripts/generate-categorization-dictionaries.ts
 */

import type { DictionaryEntry } from "../types";

export const agriculturaEntries: DictionaryEntry[] = [
  {
    target: { categorySlug: "agricultura", subcategorySlug: "tractoare-combine" },
    includeAny: [],
    confidence: 0.75,
    reason: "agricultura/tractoare-combine placeholder",
  },
  {
    target: { categorySlug: "agricultura", subcategorySlug: "remorci-agricole" },
    includeAny: [],
    confidence: 0.75,
    reason: "agricultura/remorci-agricole placeholder",
  },
  {
    target: { categorySlug: "agricultura", subcategorySlug: "echipamente-irigatii" },
    includeAny: [],
    confidence: 0.75,
    reason: "agricultura/echipamente-irigatii placeholder",
  },
  {
    target: { categorySlug: "agricultura", subcategorySlug: "animale" },
    includeAny: [],
    confidence: 0.75,
    reason: "agricultura/animale placeholder",
  },
  {
    target: { categorySlug: "agricultura", subcategorySlug: "seminte-furaje" },
    includeAny: [],
    confidence: 0.75,
    reason: "agricultura/seminte-furaje placeholder",
  }
];
