/**
 * Dictionary entries for category: arta
 * Generated by scripts/generate-categorization-dictionaries.ts
 */

import type { DictionaryEntry } from "../types";

export const artaEntries: DictionaryEntry[] = [
  {
    target: { categorySlug: "arta", subcategorySlug: "picturi" },
    includeAny: [],
    confidence: 0.75,
    reason: "arta/picturi placeholder",
  },
  {
    target: { categorySlug: "arta", subcategorySlug: "sculpturi" },
    includeAny: [],
    confidence: 0.75,
    reason: "arta/sculpturi placeholder",
  },
  {
    target: { categorySlug: "arta", subcategorySlug: "bijuterii" },
    includeAny: [],
    confidence: 0.75,
    reason: "arta/bijuterii placeholder",
  },
  {
    target: { categorySlug: "arta", subcategorySlug: "obiecte-colectie" },
    includeAny: [],
    confidence: 0.75,
    reason: "arta/obiecte-colectie placeholder",
  },
  {
    target: { categorySlug: "arta", subcategorySlug: "mobilier-epoca" },
    includeAny: [],
    confidence: 0.75,
    reason: "arta/mobilier-epoca placeholder",
  },
  {
    target: { categorySlug: "arta", subcategorySlug: "carti-rare" },
    includeAny: [],
    confidence: 0.75,
    reason: "arta/carti-rare placeholder",
  },
  {
    target: { categorySlug: "arta", subcategorySlug: "fotografie-artistica" },
    includeAny: [],
    confidence: 0.75,
    reason: "arta/fotografie-artistica placeholder",
  },
  {
    target: { categorySlug: "arta", subcategorySlug: "licitatii-caritabile" },
    includeAny: [],
    confidence: 0.75,
    reason: "arta/licitatii-caritabile placeholder",
  }
];
