/**
 * Dictionary entries for category: autovehicule
 * Generated by scripts/generate-categorization-dictionaries.ts
 */

import type { DictionaryEntry } from "../types";

export const autovehiculeEntries: DictionaryEntry[] = [
  {
    target: { categorySlug: "autovehicule", subcategorySlug: "autoturisme" },
    includeAny: ["autoturism", "masina", "automobil", "sedan", "berlina", "hatchback", "break", "auto", "diesel", "benzina", "bmw", "audi", "mercedes", "dacia", "volkswagen", "ford", "renault", "opel", "skoda"],
    excludeAny: ["camion", "tir", "motocicleta", "scuter", "remorca", "piese auto", "anvelope", "jante"],
    confidence: 0.92,
    reason: "autovehicule/autoturisme",
  },
  {
    target: { categorySlug: "autovehicule", subcategorySlug: "suv-4x4" },
    includeAny: ["suv", "4x4", "offroad", "jeep", "crossover"],
    confidence: 0.9,
    reason: "autovehicule/suv-4x4",
  },
  {
    target: { categorySlug: "autovehicule", subcategorySlug: "motociclete" },
    includeAny: ["motocicleta", "scuter", "motociclet", "moped", "atv"],
    confidence: 0.92,
    reason: "autovehicule/motociclete",
  },
  {
    target: { categorySlug: "autovehicule", subcategorySlug: "camioane" },
    includeAny: ["camion", "tir", "duba", "camioneta", "transport marfa"],
    confidence: 0.92,
    reason: "autovehicule/camioane",
  },
  {
    target: { categorySlug: "autovehicule", subcategorySlug: "remorci" },
    includeAny: ["remorca", "semiremorca", "rulota", "remorci"],
    confidence: 0.9,
    reason: "autovehicule/remorci",
  },
  {
    target: { categorySlug: "autovehicule", subcategorySlug: "autorulote" },
    includeAny: ["autorulota", "caravana", "rulota"],
    confidence: 0.88,
    reason: "autovehicule/autorulote",
  },
  {
    target: { categorySlug: "autovehicule", subcategorySlug: "vehicule-electrice" },
    includeAny: ["masina electrica", "ev", "electric", "tesla", "hybrid"],
    confidence: 0.88,
    reason: "autovehicule/vehicule-electrice",
  },
  {
    target: { categorySlug: "autovehicule", subcategorySlug: "piese-auto" },
    includeAny: ["piese auto", "anvelope", "jante", "baterie auto", "ulei motor", "filtre auto"],
    confidence: 0.9,
    reason: "autovehicule/piese-auto",
  },
];
