/**
 * Dictionary entries for category: business
 * Generated by scripts/generate-categorization-dictionaries.ts
 */

import type { DictionaryEntry } from "../types";

export const businessEntries: DictionaryEntry[] = [
  {
    target: { categorySlug: "business", subcategorySlug: "echipamente-birou" },
    includeAny: [],
    confidence: 0.75,
    reason: "business/echipamente-birou placeholder",
  },
  {
    target: { categorySlug: "business", subcategorySlug: "mobilier-comercial" },
    includeAny: [],
    confidence: 0.75,
    reason: "business/mobilier-comercial placeholder",
  },
  {
    target: { categorySlug: "business", subcategorySlug: "calculatoare-second" },
    includeAny: [],
    confidence: 0.75,
    reason: "business/calculatoare-second placeholder",
  },
  {
    target: { categorySlug: "business", subcategorySlug: "lichidari-firme" },
    includeAny: [],
    confidence: 0.75,
    reason: "business/lichidari-firme placeholder",
  },
  {
    target: { categorySlug: "business", subcategorySlug: "loturi-stocuri" },
    includeAny: [],
    confidence: 0.75,
    reason: "business/loturi-stocuri placeholder",
  }
];
