/**
 * Dictionary entries for category: casa
 * Generated by scripts/generate-categorization-dictionaries.ts
 */

import type { DictionaryEntry } from "../types";

export const casaEntries: DictionaryEntry[] = [
  {
    target: { categorySlug: "casa", subcategorySlug: "mobilier-interior" },
    includeAny: ["mobilier", "canapea", "pat", "dulap", "birou", "scaun", "masa", "comoda"],
    confidence: 0.9,
    reason: "casa/mobilier-interior",
  },
  {
    target: { categorySlug: "casa", subcategorySlug: "mobilier-exterior" },
    includeAny: ["mobilier gradina", "scaun gradina", "masa gradina", "hamac", "umbrela gradina"],
    confidence: 0.88,
    reason: "casa/mobilier-exterior",
  },
  {
    target: { categorySlug: "casa", subcategorySlug: "echipamente-gradinarit" },
    includeAny: ["tractor", "motocultivator", "cositor", "taietor iarba", "gradinarit"],
    confidence: 0.88,
    reason: "casa/echipamente-gradinarit",
  },
  {
    target: { categorySlug: "casa", subcategorySlug: "decoratiuni" },
    includeAny: ["decoratiuni", "decor", "lampa", "tablou", "vaza", "obiecte decor"],
    confidence: 0.85,
    reason: "casa/decoratiuni",
  },
  {
    target: { categorySlug: "casa", subcategorySlug: "electrocasnice" },
    includeAny: ["frigider", "frigidere", "masina spalat", "cuptor", "plita", "electrocasnic", "aspirator", "electrocasnice"],
    confidence: 0.9,
    reason: "casa/electrocasnice",
  },
];
