/**
 * Dictionary entries for category: diverse
 * Generated by scripts/generate-categorization-dictionaries.ts
 */

import type { DictionaryEntry } from "../types";

export const diverseEntries: DictionaryEntry[] = [
  {
    target: { categorySlug: "diverse", subcategorySlug: "caritabile" },
    includeAny: [],
    confidence: 0.75,
    reason: "diverse/caritabile placeholder",
  },
  {
    target: { categorySlug: "diverse", subcategorySlug: "militare-istorice" },
    includeAny: [],
    confidence: 0.75,
    reason: "diverse/militare-istorice placeholder",
  },
  {
    target: { categorySlug: "diverse", subcategorySlug: "nft-arta-digitala" },
    includeAny: [],
    confidence: 0.75,
    reason: "diverse/nft-arta-digitala placeholder",
  },
  {
    target: { categorySlug: "diverse", subcategorySlug: "colectii-private" },
    includeAny: [],
    confidence: 0.75,
    reason: "diverse/colectii-private placeholder",
  },
  {
    target: { categorySlug: "diverse", subcategorySlug: "bunuri-confiscate" },
    includeAny: [],
    confidence: 0.75,
    reason: "diverse/bunuri-confiscate placeholder",
  }
];
