/**
 * Dictionary entries for category: electronice
 * Generated by scripts/generate-categorization-dictionaries.ts
 */

import type { DictionaryEntry } from "../types";

export const electroniceEntries: DictionaryEntry[] = [
  {
    target: { categorySlug: "electronice", subcategorySlug: "laptopuri-pc" },
    includeAny: ["laptop", "notebook", "pc", "calculator", "desktop", "macbook"],
    confidence: 0.9,
    reason: "electronice/laptopuri-pc",
  },
  {
    target: { categorySlug: "electronice", subcategorySlug: "telefoane" },
    includeAny: ["telefon", "smartphone", "iphone", "telefoane mobile", "galaxy", "pixel", "xiaomi"],
    excludeAny: ["frigider", "frigidere", "masina spalat", "cuptor", "plita", "aspirator", "electrocasnic"],
    confidence: 0.92,
    reason: "electronice/telefoane",
  },
  {
    target: { categorySlug: "electronice", subcategorySlug: "tablete" },
    includeAny: ["tableta", "ipad", "tablete", "tablet"],
    confidence: 0.9,
    reason: "electronice/tablete",
  },
  {
    target: { categorySlug: "electronice", subcategorySlug: "tv-audio" },
    includeAny: ["televizor", "tv", "monitor", "sistem audio", "boxe", "home cinema"],
    confidence: 0.88,
    reason: "electronice/tv-audio",
  },
  {
    target: { categorySlug: "electronice", subcategorySlug: "console-jocuri" },
    includeAny: ["playstation", "xbox", "nintendo", "console", "jocuri video"],
    confidence: 0.9,
    reason: "electronice/console-jocuri",
  },
  {
    target: { categorySlug: "electronice", subcategorySlug: "drone-gadgeturi" },
    includeAny: ["drona", "drone", "gadget", "smartwatch", "wearable"],
    confidence: 0.85,
    reason: "electronice/drone-gadgeturi",
  },
  {
    target: { categorySlug: "electronice", subcategorySlug: "echipamente-foto" },
    includeAny: ["camera foto", "obiectiv", "aparatu foto", "foto video"],
    confidence: 0.9,
    reason: "electronice/echipamente-foto",
  },
];
