/**
 * Dictionary entries for category: executari
 * Generated by scripts/generate-categorization-dictionaries.ts
 */

import type { DictionaryEntry } from "../types";

export const executariEntries: DictionaryEntry[] = [
  {
    target: { categorySlug: "executari", subcategorySlug: "oferte-grupate" },
    includeAny: [],
    confidence: 0.75,
    reason: "executari/oferte-grupate placeholder",
  },
  {
    target: { categorySlug: "executari", subcategorySlug: "utilaje-echipamente" },
    includeAny: [],
    confidence: 0.75,
    reason: "executari/utilaje-echipamente placeholder",
  },
  {
    target: { categorySlug: "executari", subcategorySlug: "exec-imobiliare" },
    includeAny: [],
    confidence: 0.75,
    reason: "executari/exec-imobiliare placeholder",
  },
  {
    target: { categorySlug: "executari", subcategorySlug: "exec-autovehicule" },
    includeAny: [],
    confidence: 0.75,
    reason: "executari/exec-autovehicule placeholder",
  },
  {
    target: { categorySlug: "executari", subcategorySlug: "exec-industrial" },
    includeAny: [],
    confidence: 0.75,
    reason: "executari/exec-industrial placeholder",
  },
  {
    target: { categorySlug: "executari", subcategorySlug: "exec-afaceri" },
    includeAny: [],
    confidence: 0.75,
    reason: "executari/exec-afaceri placeholder",
  },
  {
    target: { categorySlug: "executari", subcategorySlug: "exec-office" },
    includeAny: [],
    confidence: 0.75,
    reason: "executari/exec-office placeholder",
  },
  {
    target: { categorySlug: "executari", subcategorySlug: "exec-altele" },
    includeAny: [],
    confidence: 0.75,
    reason: "executari/exec-altele placeholder",
  }
];
