/**
 * Dictionary entries for category: imobiliare
 * Generated by scripts/generate-categorization-dictionaries.ts
 */

import type { DictionaryEntry } from "../types";

export const imobiliareEntries: DictionaryEntry[] = [
  {
    target: { categorySlug: "imobiliare", subcategorySlug: "apartamente" },
    includeAny: ["apartament", "garsoniera", "apartamente", "bloc"],
    confidence: 0.92,
    reason: "imobiliare/apartamente",
  },
  {
    target: { categorySlug: "imobiliare", subcategorySlug: "case-vile" },
    includeAny: ["casa", "vila", "case", "vile", "casa de locuit"],
    confidence: 0.92,
    reason: "imobiliare/case-vile",
  },
  {
    target: { categorySlug: "imobiliare", subcategorySlug: "terenuri", level3Slug: "terenuri-intravilane" },
    includeAny: ["teren", "terenuri", "intravilan", "teren intravilan"],
    excludeAny: ["extravilan", "agricol"],
    confidence: 0.9,
    reason: "imobiliare/terenuri (intravilane)",
  },
  {
    target: { categorySlug: "imobiliare", subcategorySlug: "terenuri", level3Slug: "terenuri-extravilane" },
    includeAny: ["teren extravilan", "extravilan", "terenuri extravilane"],
    excludeAny: ["agricol", "teren agricol"],
    confidence: 0.9,
    reason: "imobiliare/terenuri (extravilane)",
  },
  {
    target: { categorySlug: "imobiliare", subcategorySlug: "terenuri", level3Slug: "terenuri-agricole" },
    includeAny: ["teren agricol", "agricol", "terenuri agricole", "pamant agricol"],
    confidence: 0.9,
    reason: "imobiliare/terenuri (agricole)",
  },
  {
    target: { categorySlug: "imobiliare", subcategorySlug: "spatii-comerciale" },
    includeAny: ["spatiu comercial", "spatii comerciale", "magazin", "birou comercial"],
    confidence: 0.9,
    reason: "imobiliare/spatii-comerciale",
  },
  {
    target: { categorySlug: "imobiliare", subcategorySlug: "hale-industriale" },
    includeAny: ["hala", "hale industriale", "depozit industrial"],
    confidence: 0.9,
    reason: "imobiliare/hale-industriale",
  },
  {
    target: { categorySlug: "imobiliare", subcategorySlug: "proprietati-turistice" },
    includeAny: ["proprietate turistica", "cazare", "pensiune", "complex turistic"],
    confidence: 0.88,
    reason: "imobiliare/proprietati-turistice",
  },
];
