/**
 * Registry of all dictionary entries (all categories/subcategories).
 * Generated by scripts/generate-categorization-dictionaries.ts
 */

import type { DictionaryEntry } from "../types";
import { imobiliareEntries } from "./imobiliare";
import { executariEntries } from "./executari";
import { autovehiculeEntries } from "./autovehicule";
import { utilajeEntries } from "./utilaje";
import { electroniceEntries } from "./electronice";
import { diverseEntries } from "./diverse";
import { artaEntries } from "./arta";
import { casaEntries } from "./casa";
import { modaEntries } from "./moda";
import { mama_copilEntries } from "./mama-copil";
import { agriculturaEntries } from "./agricultura";
import { maritimeEntries } from "./maritime";
import { businessEntries } from "./business";
import { materialeEntries } from "./materiale";

export { imobiliareEntries } from "./imobiliare";
export { executariEntries } from "./executari";
export { autovehiculeEntries } from "./autovehicule";
export { utilajeEntries } from "./utilaje";
export { electroniceEntries } from "./electronice";
export { diverseEntries } from "./diverse";
export { artaEntries } from "./arta";
export { casaEntries } from "./casa";
export { modaEntries } from "./moda";
export { mama_copilEntries } from "./mama-copil";
export { agriculturaEntries } from "./agricultura";
export { maritimeEntries } from "./maritime";
export { businessEntries } from "./business";
export { materialeEntries } from "./materiale";

export const ALL_DICTIONARY_ENTRIES: DictionaryEntry[] = [
  ...imobiliareEntries,
  ...executariEntries,
  ...autovehiculeEntries,
  ...utilajeEntries,
  ...electroniceEntries,
  ...diverseEntries,
  ...artaEntries,
  ...casaEntries,
  ...modaEntries,
  ...mama_copilEntries,
  ...agriculturaEntries,
  ...maritimeEntries,
  ...businessEntries,
  ...materialeEntries,
];
