/**
 * Dictionary entries for category: mama-copil
 * Generated by scripts/generate-categorization-dictionaries.ts
 */

import type { DictionaryEntry } from "../types";

export const mama_copilEntries: DictionaryEntry[] = [
  {
    target: { categorySlug: "mama-copil", subcategorySlug: "haine-copil" },
    includeAny: ["haine copil", "imbracaminte copil", "body bebelusi", "costum copil"],
    confidence: 0.9,
    reason: "mama-copil/haine-copil",
  },
  {
    target: { categorySlug: "mama-copil", subcategorySlug: "incaltaminte-copil" },
    includeAny: ["pantofi copil", "incaltaminte copil", "ghete copil", "papuci copil"],
    confidence: 0.88,
    reason: "mama-copil/incaltaminte-copil",
  },
  {
    target: { categorySlug: "mama-copil", subcategorySlug: "jucarii" },
    includeAny: ["jucarie", "jucarii", "lego", "papusa", "masinuta", "joc copil"],
    confidence: 0.92,
    reason: "mama-copil/jucarii",
  },
  {
    target: { categorySlug: "mama-copil", subcategorySlug: "mobilier-copil" },
    includeAny: ["patut copil", "comoda copil", "mobilier copil", "dulap copil"],
    confidence: 0.88,
    reason: "mama-copil/mobilier-copil",
  },
  {
    target: { categorySlug: "mama-copil", subcategorySlug: "cosul-copilului" },
    includeAny: ["cos copil", "cosul copilului", "pat bebelus", "pat bebelusi"],
    confidence: 0.9,
    reason: "mama-copil/cosul-copilului",
  },
  {
    target: { categorySlug: "mama-copil", subcategorySlug: "ingrijire-bebelusi" },
    includeAny: ["ingrijire bebelus", "bebelus", "bebelusi", "pampers", "creme bebelus"],
    confidence: 0.88,
    reason: "mama-copil/ingrijire-bebelusi",
  },
  {
    target: { categorySlug: "mama-copil", subcategorySlug: "scaune-auto-copil" },
    includeAny: ["scaun auto copil", "scaun auto bebelus", "sistem retentie copil"],
    confidence: 0.9,
    reason: "mama-copil/scaune-auto-copil",
  },
  {
    target: { categorySlug: "mama-copil", subcategorySlug: "carucioare" },
    includeAny: ["carucior", "carucioare", "trotineta copil", "tricicleta copil"],
    confidence: 0.92,
    reason: "mama-copil/carucioare",
  },
  {
    target: { categorySlug: "mama-copil", subcategorySlug: "hranire-copil" },
    includeAny: ["hranire copil", "blitz", "suculet", "biberon", "sterilizator"],
    confidence: 0.88,
    reason: "mama-copil/hranire-copil",
  },
];
