/**
 * Dictionary entries for category: maritime
 * Generated by scripts/generate-categorization-dictionaries.ts
 */

import type { DictionaryEntry } from "../types";

export const maritimeEntries: DictionaryEntry[] = [
  {
    target: { categorySlug: "maritime", subcategorySlug: "barci-iahturi" },
    includeAny: [],
    confidence: 0.75,
    reason: "maritime/barci-iahturi placeholder",
  },
  {
    target: { categorySlug: "maritime", subcategorySlug: "motoare-marine" },
    includeAny: [],
    confidence: 0.75,
    reason: "maritime/motoare-marine placeholder",
  },
  {
    target: { categorySlug: "maritime", subcategorySlug: "avioane" },
    includeAny: [],
    confidence: 0.75,
    reason: "maritime/avioane placeholder",
  },
  {
    target: { categorySlug: "maritime", subcategorySlug: "drone-industriale" },
    includeAny: [],
    confidence: 0.75,
    reason: "maritime/drone-industriale placeholder",
  }
];
