/**
 * Dictionary entries for category: materiale
 * Generated by scripts/generate-categorization-dictionaries.ts
 */

import type { DictionaryEntry } from "../types";

export const materialeEntries: DictionaryEntry[] = [
  {
    target: { categorySlug: "materiale", subcategorySlug: "ciment-caramida" },
    includeAny: [],
    confidence: 0.75,
    reason: "materiale/ciment-caramida placeholder",
  },
  {
    target: { categorySlug: "materiale", subcategorySlug: "materiale-izolatie" },
    includeAny: [],
    confidence: 0.75,
    reason: "materiale/materiale-izolatie placeholder",
  },
  {
    target: { categorySlug: "materiale", subcategorySlug: "feronerie-unelte" },
    includeAny: [],
    confidence: 0.75,
    reason: "materiale/feronerie-unelte placeholder",
  },
  {
    target: { categorySlug: "materiale", subcategorySlug: "usi-ferestre" },
    includeAny: [],
    confidence: 0.75,
    reason: "materiale/usi-ferestre placeholder",
  }
];
