/**
 * Dictionary entries for category: moda
 * Generated by scripts/generate-categorization-dictionaries.ts
 */

import type { DictionaryEntry } from "../types";

export const modaEntries: DictionaryEntry[] = [
  {
    target: { categorySlug: "moda", subcategorySlug: "haine-designer" },
    includeAny: ["rochie", "bluza", "pantaloni", "geaca", "tricou", "costum", "palton", "haine designer"],
    confidence: 0.9,
    reason: "moda/haine-designer",
  },
  {
    target: { categorySlug: "moda", subcategorySlug: "incaltaminte" },
    includeAny: ["pantofi", "ghete", "cizme", "tenisi", "sandale", "incaltaminte", "adidasi"],
    confidence: 0.9,
    reason: "moda/incaltaminte",
  },
  {
    target: { categorySlug: "moda", subcategorySlug: "genti-accesorii" },
    includeAny: ["geanta", "portofel", "curea", "esarf", "accesorii moda"],
    confidence: 0.88,
    reason: "moda/genti-accesorii",
  },
  {
    target: { categorySlug: "moda", subcategorySlug: "parfumuri-cosmetice" },
    includeAny: ["parfum", "cosmetice", "makeup", "crema", "parfumuri"],
    confidence: 0.88,
    reason: "moda/parfumuri-cosmetice",
  },
  {
    target: { categorySlug: "moda", subcategorySlug: "ceasuri-lux" },
    includeAny: ["ceas", "ceasuri", "ceas lux", "ceasuri de mana"],
    confidence: 0.88,
    reason: "moda/ceasuri-lux",
  },
];
