/**
 * Dictionary entries for category: utilaje
 * Generated by scripts/generate-categorization-dictionaries.ts
 */

import type { DictionaryEntry } from "../types";

export const utilajeEntries: DictionaryEntry[] = [
  {
    target: { categorySlug: "utilaje", subcategorySlug: "utilaje-constructii" },
    includeAny: [],
    confidence: 0.75,
    reason: "utilaje/utilaje-constructii placeholder",
  },
  {
    target: { categorySlug: "utilaje", subcategorySlug: "utilaje-agricole" },
    includeAny: [],
    confidence: 0.75,
    reason: "utilaje/utilaje-agricole placeholder",
  },
  {
    target: { categorySlug: "utilaje", subcategorySlug: "tractoare-combine" },
    includeAny: [],
    confidence: 0.75,
    reason: "utilaje/tractoare-combine placeholder",
  },
  {
    target: { categorySlug: "utilaje", subcategorySlug: "echipamente-forestiere" },
    includeAny: [],
    confidence: 0.75,
    reason: "utilaje/echipamente-forestiere placeholder",
  },
  {
    target: { categorySlug: "utilaje", subcategorySlug: "generatoare" },
    includeAny: [],
    confidence: 0.75,
    reason: "utilaje/generatoare placeholder",
  },
  {
    target: { categorySlug: "utilaje", subcategorySlug: "scule-profesionale" },
    includeAny: [],
    confidence: 0.75,
    reason: "utilaje/scule-profesionale placeholder",
  },
  {
    target: { categorySlug: "utilaje", subcategorySlug: "echipamente-ateliere" },
    includeAny: [],
    confidence: 0.75,
    reason: "utilaje/echipamente-ateliere placeholder",
  },
  {
    target: { categorySlug: "utilaje", subcategorySlug: "echipamente-electrice" },
    includeAny: [],
    confidence: 0.75,
    reason: "utilaje/echipamente-electrice placeholder",
  }
];
