/**
 * Configurare categorii cu Level 3
 * Level 1: category, Level 2: subcategory, Level 3: sub_subcategory
 */

import { PIESE_AUTO_LEVEL3_SLUGS } from "@/lib/piese-auto/tip-piesa-level3";

// ========== MĂRIMI (XS, S, M, L, XL) – pentru haine, încălțăminte etc. ==========
export const SIZE_OPTIONS_CLOTHING = ['XXS', 'XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL'] as const;
export const SIZE_OPTIONS_SHOES = ['34', '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48', '49', '50'] as const;
export const SIZE_OPTIONS_KIDS_CM = ['56', '62', '68', '74', '80', '86', '92', '98', '104', '110', '116', '122', '128', '134', '140', '146', '152', '158', '164'] as const;
export const SIZE_OPTIONS_UNIVERSAL = [...SIZE_OPTIONS_CLOTHING, ...SIZE_OPTIONS_SHOES, 'Unica'] as const;

/** Subcategorii care au selector de mărime – tipul de mărimi disponibile */
export const SUBCATEGORIES_WITH_SIZE: Record<string, 'clothing' | 'shoes' | 'kids' | 'universal'> = {
  'haine-designer': 'clothing',
  'incaltaminte': 'shoes',
  'genti-accesorii': 'clothing',
  'haine-copil': 'kids',
  'incaltaminte-copil': 'kids',
  'Haine de Designer': 'clothing',
  'Încălțăminte': 'shoes',
  'Genți & Accesorii': 'clothing',
  'Haine copil': 'kids',
  'Încălțăminte copil': 'kids',
};

export function getSizeOptions(subcategoryKeyOrName: string): readonly string[] {
  const type = SUBCATEGORIES_WITH_SIZE[subcategoryKeyOrName];
  if (!type) return [];
  switch (type) {
    case 'clothing':
      return SIZE_OPTIONS_CLOTHING;
    case 'shoes':
      return SIZE_OPTIONS_SHOES;
    case 'kids':
      return [...SIZE_OPTIONS_KIDS_CM, ...SIZE_OPTIONS_CLOTHING];
    case 'universal':
      return [...SIZE_OPTIONS_UNIVERSAL];
    default:
      return [];
  }
}

export const CATEGORY_LEVEL_3: Record<string, string[]> = {
  // ========== IMOBILIARE ==========
  'apartamente': ['1-camere', '2-camere', '3-camere', '4-camere', '5-camere-plus', 'duplex', 'loft', 'penthouse'],
  'case-vile': ['casa-individuala', 'vila', 'casa-tara', 'casa-gard', 'casa-dubla'],
  'terenuri': ['terenuri-intravilane', 'terenuri-extravilane', 'terenuri-agricole'],
  'terenuri-intravilane': ['teren-constructii', 'teren-parcela', 'teren-comercial', 'teren-industrial'],
  'terenuri-agricole': ['teren-arabil', 'livada', 'padure', 'pajiste', 'teren-mixt'],
  'spatii-comerciale': ['birouri', 'magazin', 'restaurant', 'depozit', 'showroom', 'spatiu-mixed-use'],
  'hale-industriale': ['hala-producție', 'hala-depozitare', 'hala-logistica', 'atelier'],
  'proprietati-turistice': ['apartament-turistic', 'casa-turistica', 'pensiune', 'teren-turistic'],

  // ========== EXECUTĂRI (categorii comune pentru Executori și Insolvență - doar 6) ==========
  'exec-imobiliare': [],
  'exec-autovehicule': [],
  'exec-industrial': [],
  'exec-afaceri': [],
  'exec-office': [],
  'exec-altele': [],

  // ========== AUTOVEHICULE ==========
  'autoturisme': ['sedan', 'hatchback', 'suv', 'coupe', 'cabrio', 'break', 'monovolum', 'pick-up', 'compact', 'berlina'],
  'suv-4x4': ['suv-mic', 'suv-compact', 'suv-mare', 'suv-lux', '4x4-offroad', 'crossover'],
  'motociclete': ['sport', 'cruiser', 'touring', 'enduro', 'scooter', 'atv', 'motocicleta-electrica'],
  'camioane': ['camion-mic', 'camion-mediu', 'camion-mare', 'tir', 'basculanta', 'cisterna'],
  'remorci': ['remorca-mica', 'remorca-mare', 'semiremorca', 'remorca-speciala', 'remorca-agricola'],
  'autorulote': ['caravana', 'rulota', 'semi-integrala', 'integrala', 'micro-rulota'],
  'vehicule-electrice': ['tesla', 'bmw-i', 'audi-e-tron', 'mercedes-eq', 'dacia-spring', 'renault-zoe', 'vw-id', 'hyundai-kona-electric'],
  /** Aliniat la Tip piesă din anunț manual (slug-uri din lib/piese-auto/tip-piesa-level3). */
  'piese-auto': [...PIESE_AUTO_LEVEL3_SLUGS],

  // ========== UTILAJE ==========
  'utilaje-constructii': ['excavator', 'buldozer', 'macara', 'betoniera', 'compresor', 'scafandru', 'demolator', 'incarcator', 'tractoare-constructii'],
  'utilaje-agricole': ['tractor', 'combina', 'plug', 'semanator', 'cositoare', 'presa-bala', 'pulverizator', 'remorca-agricola'],
  'echipamente-forestiere': ['ferastrau-lant', 'tractor-forestier', 'incarcator-forestier', 'macara-forestiera', 'chiper'],
  'generatoare': ['generator-benzina', 'generator-diesel', 'generator-gaz', 'ups', 'invertor'],
  'scule-profesionale': ['perforator', 'flex', 'compresor', 'scula-electrica', 'scula-manuala', 'sistem-masurare'],
  'echipamente-ateliere': ['ridicatoare', 'echipament-vulcanizare', 'echipament-spalatorie', 'sisteme-diagnostice'],
  'echipamente-electrice': ['sudura', 'masina-taiere', 'masina-polizare', 'echipament-incalzire'],

  // ========== ARTĂ ==========
  'picturi': ['ulei', 'acrilic', 'acvarela', 'pastel', 'desen', 'gravura', 'contemporan', 'clasic'],
  'sculpturi': ['bronz', 'piatra', 'lemn', 'metal', 'ceramica', 'sticla', 'contemporan', 'clasic'],
  'bijuterii': ['coliere', 'cercei', 'bratari', 'inele', 'pandantive', 'ceasuri', 'bijuterii-aur', 'bijuterii-argint', 'bijuterii-cosmetice'],
  'obiecte-colectie': ['monede', 'timbru', 'figurine', 'jucarii-vintage', 'obiecte-militare', 'obiecte-stiintifice'],
  'mobilier-epoca': ['baroc', 'rococo', 'victorian', 'art-deco', 'retro', 'mid-century'],
  'carti-rare': ['manuscrise', 'editii-prima', 'autografe', 'harti', 'gravuri-vechi'],
  'fotografie-artistica': ['alb-negru', 'color', 'digital', 'analog', 'polaroid'],
  'licitatii-caritabile': ['picturi', 'obiecte-semnate', 'experiente', 'intalniri'],

  // ========== ELECTRONICE ==========
  'laptopuri-pc': ['dell', 'hp', 'lenovo', 'asus', 'acer', 'apple', 'msi', 'gigabyte', 'razer', 'microsoft-surface', 'huawei', 'samsung'],
  'telefoane': ['iphone', 'samsung', 'xiaomi', 'huawei', 'oppo', 'oneplus', 'google-pixel', 'nokia', 'motorola', 'sony', 'lg', 'realme', 'honor'],
  'tablete': ['ipad', 'samsung-tab', 'huawei-matepad', 'lenovo-tab', 'amazon-fire', 'microsoft-surface'],
  'tv-audio': ['tv-led', 'tv-oled', 'tv-qled', 'soundbar', 'home-cinema', 'casti', 'boxe', 'proiector'],
  'console-jocuri': ['playstation', 'xbox', 'nintendo-switch', 'pc-gaming', 'accesorii-jocuri', 'jocuri-fizice'],
  'drone-gadgeturi': ['drone-recreationale', 'drone-pro', 'action-cam', 'smartwatch', 'casti-wireless', 'boxe-portabile'],
  'echipamente-foto': ['camere-dslr', 'camere-mirrorless', 'obiective', 'blitz', 'trepied', 'gimbal', 'accesorii-foto'],

  // ========== CASA ==========
  'mobilier-interior': ['canapele', 'paturi', 'mese', 'scaune', 'dulapuri', 'rafturi', 'birouri', 'saltele'],
  'mobilier-exterior': ['mese-gradina', 'scaune-gradina', 'balansoare', 'umbrele', 'hamac', 'leagane'],
  'echipamente-gradinarit': ['tractoare-gradina', 'cositori', 'pompe-apa', 'irigatii', 'sere', 'gradinare'],
  'decoratiuni': ['tablouri', 'vaze', 'obiecte-decor', 'lumanari', 'oglinzi', 'covor'],
  'electrocasnice': ['frigidere', 'cuptoare', 'masini-spalat', 'masini-uscator', 'aspiratoare', 'ceainiță', 'altele'],

  // ========== MODĂ ==========
  'haine-designer': ['rochii', 'costume', 'paltoane', 'jachete', 'tricouri', 'pantaloni', 'fuste', 'bluze'],
  'incaltaminte': ['pantofi', 'cizme', 'sneakeri', 'sandalii', 'papuci', 'incaltaminte-sport'],
  'genti-accesorii': ['genti', 'rucsacuri', 'portofele', 'centuri', 'esarfe', 'ochelari'],
  'parfumuri-cosmetice': ['parfumuri', 'creme', 'make-up', 'ingrijire-par', 'produse-barbati'],
  'ceasuri-lux': ['rolex', 'omega', 'cartier', 'patek-philippe', 'audemars-piguet', 'tag-heuer', 'altele'],

  // ========== MAMA ȘI COPILUL ==========
  'haine-copil': ['0-12-luni', '1-3-ani', '3-6-ani', '6-12-ani', 'haine-bebelusi', 'costume-copil'],
  'incaltaminte-copil': ['pantofi-copil', 'cizme-copil', 'sandalii-copil', 'papuci-casa'],
  'jucarii': ['jucarii-educative', 'jucarii-electronice', 'puzzle', 'figurine', 'masini-jucarii', 'jucarii-exterior'],
  'mobilier-copil': ['patut', 'comoda', 'dulap-copil', 'birou-copil', 'rafturi', 'pui-sertar'],
  'cosul-copilului': ['carucior', 'sacosa-copil', 'pat-purtator', 'ham', 'accesorii-puericultura'],
  'ingrijire-bebelusi': ['sterilizatoare', 'termometre', 'aspiratoare-nas', 'umidificatoare', 'monitoare-bebelus'],
  'scaune-auto-copil': ['grupa-0', 'grupa-0-plus', 'grupa-1', 'grupa-2-3', 'scaun-izofix', 'baza-auto'],
  'carucioare': ['carucior-complet', 'carucior-simplu', 'twin', 'carucior-sport', 'accesorii-carucior'],
  'hranire-copil': ['biberoane', 'tetine', 'sterilizatoare', 'incalzitoare', 'mameloane', 'tacamuri-copil'],

  // ========== AGRICULTURĂ ==========
  'tractoare-combine': ['tractor-mic', 'tractor-mediu', 'tractor-mare', 'combina-cereale', 'combina-porumb', 'accesorii-tractor'],
  'remorci-agricole': ['remorca-platforma', 'remorca-basculanta', 'remorca-cisterna', 'remorca-speciala'],
  'echipamente-irigatii': ['pompe', 'conducte', 'stropitoare', 'sisteme-pivot', 'gouturare'],
  'animale': ['bovine', 'ovine', 'porcine', 'pasarim', 'echide', 'altele'],
  'seminte-furaje': ['seminte', 'furaje', 'ingrasaminte', 'protectie-vegetala', 'tratamente'],

  // ========== MARITIME ==========
  'barci-iahturi': ['barca-mica', 'barca-mare', 'iaht', 'velier', 'skijet', 'canot', 'kayak'],
  'motoare-marine': ['motor-outboard', 'motor-inboard', 'motor-electronic', 'pompe-bord'],
  'avioane': ['avion-usoar', 'ultralight', 'paramotor', 'planor', 'elicopter-mic'],
  'drone-industriale': ['drone-inspecție', 'drone-agriculture', 'drone-mapping', 'drone-transport'],

  // ========== BUSINESS ==========
  'echipamente-birou': ['calculatoare', 'imprimante', 'scanere', 'mobilier-birou', 'echipamente-prezentare'],
  'mobilier-comercial': ['vitrine', 'rafturi-comerciale', 'case-incarcare', 'mese-showroom', 'scaune-receptie'],
  'calculatoare-second': ['laptop-second', 'desktop-second', 'workstation', 'server', 'monitoare'],
  'lichidari-firme': ['stocuri', 'echipamente', 'mobilier', 'utilaje', 'loturi-mixte'],
  'loturi-stocuri': ['electronice', 'haine', 'cosmetice', 'alimente', 'materiale', 'diverse'],

  // ========== MATERIALE CONSTRUCȚII ==========
  'ciment-caramida': ['ciment', 'caramida', 'beton', 'otel-constructii', 'placi', 'blocuri'],
  'materiale-izolatie': ['vata-minerala', 'polistiren', 'polistiren-extrus', 'sticla-spuma', 'termoizolatie-pereti', 'termoizolatie-acoperis', 'folie-termoizolanta'],
  'feronerie-unelte': ['balamale', 'chei', 'serruri', 'unelte-manuale', 'unelte-electrice', 'echipamente-protectie'],
  'usi-ferestre': ['usi-interior', 'usi-exterior', 'ferestre-pvc', 'ferestre-aluminiu', 'ferestre-lemn', 'tamplarie'],

  // ========== DIVERSE ==========
  'caritabile': ['picturi', 'obiecte-semnate', 'experiente', 'donatii-speciale'],
  'militare-istorice': ['uniformes', 'decoratii', 'obiecte-istorice', 'arma-colectie', 'documente'],
  'nft-arta-digitala': ['nft-arta', 'nft-muzica', 'nft-collectibles', 'nft-utility'],
  'colectii-private': ['monede', 'timbru', 'figurine', 'vinuri', 'whisky', 'altele'],
  'bunuri-confiscate': ['electronice', 'autovehicule', 'imobiliare', 'obiecte-valoare', 'diverse'],
};

export const CATEGORY_LEVEL_3_NAMES: Record<string, string> = {
  // Imobiliare
  '1-camere': '1 camere',
  '2-camere': '2 camere',
  '3-camere': '3 camere',
  '4-camere': '4 camere',
  '5-camere-plus': '5+ camere',
  'duplex': 'Duplex',
  'loft': 'Loft',
  'penthouse': 'Penthouse',
  'casa-individuala': 'Casă individuală',
  'vila': 'Vilă',
  'casa-tara': 'Casă la țară',
  'casa-gard': 'Casă cu grădină',
  'casa-dubla': 'Casă dublă',
  'terenuri-intravilane': 'Terenuri intravilane',
  'terenuri-extravilane': 'Terenuri extravilane',
  'terenuri-agricole': 'Terenuri agricole',
  'teren-constructii': 'Teren construcții',
  'teren-parcela': 'Teren parcelă',
  'teren-comercial': 'Teren comercial',
  'teren-industrial': 'Teren industrial',
  'teren-arabil': 'Teren arabil',
  'livada': 'Livadă',
  'padure': 'Pădure',
  'pajiste': 'Pajiște',
  'teren-mixt': 'Teren mixt',
  'birouri': 'Birouri',
  'magazin': 'Magazin',
  'restaurant': 'Restaurant',
  'depozit': 'Depozit',
  'showroom': 'Showroom',
  'spatiu-mixed-use': 'Spațiu mixt',
  'hala-producție': 'Hală producție',
  'hala-depozitare': 'Hală depozitare',
  'hala-logistica': 'Hală logistică',
  'atelier': 'Atelier',
  'apartament-turistic': 'Apartament turistic',
  'casa-turistica': 'Casă turistică',
  'pensiune': 'Pensiune',
  'teren-turistic': 'Teren turistic',

  // Executări silite
  'apartamente': 'Apartamente',
  'case': 'Case',
  'terenuri': 'Terenuri',
  'spatii-comerciale': 'Spații comerciale',
  'hale': 'Hale',
  'intravilane': 'Intravilane',
  'agricole': 'Agricole',
  'forestiere': 'Forestiere',
  'autoturisme': 'Autoturisme',
  'utilaje': 'Utilaje',
  'remorci': 'Remorci',
  'motociclete': 'Motociclete',
  'constructii': 'Construcții',
  'industrial': 'Industrial',
  'participatii': 'Participații',
  'drepturi-sociale': 'Drepturi sociale',
  'titluri': 'Titluri',
  'creante-fiscale': 'Creanțe fiscale',
  'creante-bancare': 'Creanțe bancare',
  'alte-creante': 'Alte creanțe',
  'stocuri': 'Stocuri',
  'echipamente': 'Echipamente',
  'diverse': 'Diverse',

  // Autovehicule
  'sedan': 'Sedan',
  'hatchback': 'Hatchback',
  'suv': 'SUV',
  'coupe': 'Coupé',
  'cabrio': 'Cabrio',
  'break': 'Break',
  'monovolum': 'Monovolum',
  'pick-up': 'Pick-up',
  'compact': 'Compact',
  'berlina': 'Berlina',
  'suv-mic': 'SUV mic',
  'suv-compact': 'SUV compact',
  'suv-mare': 'SUV mare',
  'suv-lux': 'SUV lux',
  '4x4-offroad': '4x4 off-road',
  'crossover': 'Crossover',
  'sport': 'Sport',
  'cruiser': 'Cruiser',
  'touring': 'Touring',
  'enduro': 'Enduro',
  'scooter': 'Scooter',
  'atv': 'ATV',
  'motocicleta-electrica': 'Motocicletă electrică',
  'camion-mic': 'Camion mic',
  'camion-mediu': 'Camion mediu',
  'camion-mare': 'Camion mare',
  'tir': 'TIR',
  'basculanta': 'Basculantă',
  'cisterna': 'Cisternă',
  'remorca-mica': 'Remorcă mică',
  'remorca-mare': 'Remorcă mare',
  'semiremorca': 'Semiremorcă',
  'remorca-speciala': 'Remorcă specială',
  'remorca-agricola': 'Remorcă agricolă',
  'caravana': 'Caravană',
  'rulota': 'Rulotă',
  'semi-integrala': 'Semi-integrală',
  'integrala': 'Integrală',
  'micro-rulota': 'Micro-rulotă',
  'tesla': 'Tesla',
  'bmw-i': 'BMW i',
  'audi-e-tron': 'Audi e-tron',
  'mercedes-eq': 'Mercedes EQ',
  'dacia-spring': 'Dacia Spring',
  'renault-zoe': 'Renault Zoe',
  'vw-id': 'VW ID',
  'hyundai-kona-electric': 'Hyundai Kona Electric',

  // Piese auto
  'aripa': 'Aripă',
  'capota': 'Capotă',
  'far': 'Far',
  'bara': 'Bară',
  'usi': 'Uși',
  'oglinzi': 'Oglinzi',
  'parbriz': 'Parbriz',
  'geam': 'Geam',
  'bloc-motor': 'Bloc motor',
  'transmisie': 'Transmisie',
  'amortizor': 'Amortizor',
  'janta': 'Jantă',
  'cardan': 'Cardan',
  'etrier': 'Etrier',
  'placute-frane': 'Pla cuțe frâne',
  'filtre': 'Filtre',
  'bujii': 'Bujii',
  'distributie': 'Distribuție',
  'alternator': 'Alternator',
  'baterie-auto': 'Baterie auto',

  // Utilaje
  'excavator': 'Excavator',
  'buldozer': 'Buldozer',
  'macara': 'Macara',
  'betoniera': 'Betoniera',
  'compresor': 'Compresor',
  'scafandru': 'Scafandru',
  'demolator': 'Demolator',
  'incarcator': 'Încărcător',
  'tractoare-constructii': 'Tractoare construcții',
  'tractor': 'Tractor',
  'combina': 'Combina',
  'plug': 'Plug',
  'semanator': 'Semănător',
  'cositoare': 'Coșitior',
  'presa-bala': 'Presă bală',
  'pulverizator': 'Pulverizator',
  'ferastrau-lant': 'Ferăstrău lanț',
  'tractor-forestier': 'Tractor forestier',
  'incarcator-forestier': 'Încărcător forestier',
  'macara-forestiera': 'Macara forestieră',
  'chiper': 'Chiper',
  'generator-benzina': 'Generator benzină',
  'generator-diesel': 'Generator diesel',
  'generator-gaz': 'Generator gaz',
  'ups': 'UPS',
  'invertor': 'Invertor',
  'perforator': 'Perforator',
  'flex': 'Flex',
  'scula-electrica': 'Sculă electrică',
  'scula-manuala': 'Sculă manuală',
  'sistem-masurare': 'Sistem măsurare',
  'ridicatoare': 'Ridicătoare',
  'echipament-vulcanizare': 'Echipament vulcanizare',
  'echipament-spalatorie': 'Echipament spălătorie',
  'sisteme-diagnostice': 'Sisteme diagnostice',
  'sudura': 'Sudură',
  'masina-taiere': 'Mașină tăiere',
  'masina-polizare': 'Mașină polizare',
  'echipament-incalzire': 'Echipament încălzire',

  // Artă
  'ulei': 'Ulei',
  'acrilic': 'Acrilic',
  'acvarela': 'Acuarela',
  'pastel': 'Pastel',
  'desen': 'Desen',
  'gravura': 'Gravură',
  'contemporan': 'Contemporan',
  'clasic': 'Clasic',
  'bronz': 'Bronz',
  'piatra': 'Piatră',
  'lemn': 'Lemn',
  'metal': 'Metal',
  'ceramica': 'Ceramică',
  'sticla': 'Sticlă',
  'coliere': 'Coliere',
  'cercei': 'Cercei',
  'bratari': 'Brățări',
  'inele': 'Inele',
  'pandantive': 'Pandantive',
  'ceasuri': 'Ceasuri',
  'bijuterii-aur': 'Bijuterii aur',
  'bijuterii-argint': 'Bijuterii argint',
  'bijuterii-cosmetice': 'Bijuterii cosmetice',
  'monede': 'Monede',
  'timbru': 'Timbru',
  'figurine': 'Figurine',
  'jucarii-vintage': 'Jucării vintage',
  'obiecte-militare': 'Obiecte militare',
  'obiecte-stiintifice': 'Obiecte științifice',
  'baroc': 'Baroc',
  'rococo': 'Rococo',
  'victorian': 'Victorian',
  'art-deco': 'Art Deco',
  'retro': 'Retro',
  'mid-century': 'Mid-Century',
  'manuscrise': 'Manuscrise',
  'editii-prima': 'Ediții prima',
  'autografe': 'Autografe',
  'harti': 'Hărți',
  'gravuri-vechi': 'Gravuri vechi',
  'alb-negru': 'Alb-negru',
  'color': 'Color',
  'digital': 'Digital',
  'analog': 'Analog',
  'polaroid': 'Polaroid',
  'obiecte-semnate': 'Obiecte semnate',
  'experiente': 'Experiențe',
  'intalniri': 'Întâlniri',

  // Electronice
  'iphone': 'iPhone',
  'samsung': 'Samsung',
  'xiaomi': 'Xiaomi',
  'huawei': 'Huawei',
  'oppo': 'Oppo',
  'oneplus': 'OnePlus',
  'google-pixel': 'Google Pixel',
  'nokia': 'Nokia',
  'motorola': 'Motorola',
  'sony': 'Sony',
  'lg': 'LG',
  'realme': 'Realme',
  'honor': 'Honor',
  'dell': 'Dell',
  'hp': 'HP',
  'lenovo': 'Lenovo',
  'asus': 'Asus',
  'acer': 'Acer',
  'apple': 'Apple',
  'msi': 'MSI',
  'gigabyte': 'Gigabyte',
  'razer': 'Razer',
  'microsoft-surface': 'Microsoft Surface',
  'ipad': 'iPad',
  'samsung-tab': 'Samsung Tab',
  'huawei-matepad': 'Huawei MatePad',
  'lenovo-tab': 'Lenovo Tab',
  'amazon-fire': 'Amazon Fire',
  'tv-led': 'TV LED',
  'tv-oled': 'TV OLED',
  'tv-qled': 'TV QLED',
  'soundbar': 'Soundbar',
  'home-cinema': 'Home cinema',
  'casti': 'Căști',
  'boxe': 'Boxe',
  'proiector': 'Proiector',
  'playstation': 'PlayStation',
  'xbox': 'Xbox',
  'nintendo-switch': 'Nintendo Switch',
  'pc-gaming': 'PC gaming',
  'accesorii-jocuri': 'Accesorii jocuri',
  'jocuri-fizice': 'Jocuri fizice',
  'drone-recreationale': 'Drone recreative',
  'drone-pro': 'Drone profesionale',
  'action-cam': 'Action cam',
  'smartwatch': 'Smartwatch',
  'casti-wireless': 'Căști wireless',
  'boxe-portabile': 'Boxe portabile',
  'camere-dslr': 'Camere DSLR',
  'camere-mirrorless': 'Camere mirrorless',
  'obiective': 'Obiective',
  'blitz': 'Blitz',
  'trepied': 'Trepied',
  'gimbal': 'Gimbal',
  'accesorii-foto': 'Accesorii foto',

  // Casă
  'canapele': 'Canapele',
  'paturi': 'Paturi',
  'mese': 'Mese',
  'scaune': 'Scaune',
  'dulapuri': 'Dulapuri',
  'rafturi': 'Rafturi',
  'saltele': 'Saltele',
  'mese-gradina': 'Mese grădină',
  'scaune-gradina': 'Scaune grădină',
  'balansoare': 'Balansoare',
  'umbrele': 'Umbrele',
  'hamac': 'Hamac',
  'leagane': 'Leagăne',
  'tractoare-gradina': 'Tractoare grădină',
  'cositori': 'Coșitori',
  'pompe-apa': 'Pompe apă',
  'irigatii': 'Irigații',
  'sere': 'Sere',
  'gradinare': 'Grădinăre',
  'tablouri': 'Tablouri',
  'vaze': 'Vaze',
  'obiecte-decor': 'Obiecte decor',
  'lumanari': 'Lumânări',
  'covor': 'Covor',
  'frigidere': 'Frigidere',
  'cuptoare': 'Cuptoare',
  'masini-spalat': 'Mașini spălat',
  'masini-uscator': 'Mașini uscător',
  'aspiratoare': 'Aspiratoare',
  'ceainiță': 'Ceainic',
  'altele': 'Altele',

  // Modă
  'rochii': 'Rochii',
  'costume': 'Costume',
  'paltoane': 'Paltoane',
  'jachete': 'Jachete',
  'tricouri': 'Tricouri',
  'pantaloni': 'Pantaloni',
  'fuste': 'Fuste',
  'bluze': 'Bluze',
  'pantofi': 'Pantofi',
  'cizme': 'Cizme',
  'sneakeri': 'Sneakeri',
  'sandalii': 'Sandalii',
  'papuci': 'Papuci',
  'incaltaminte-sport': 'Încălțăminte sport',
  'genti': 'Genți',
  'rucsacuri': 'Rucsacuri',
  'portofele': 'Portofele',
  'centuri': 'Centuri',
  'esarfe': 'Eșarfe',
  'ochelari': 'Ochelari',
  'parfumuri': 'Parfumuri',
  'creme': 'Creme',
  'make-up': 'Make-up',
  'ingrijire-par': 'Îngrijire păr',
  'produse-barbati': 'Produse bărbați',
  'rolex': 'Rolex',
  'omega': 'Omega',
  'cartier': 'Cartier',
  'patek-philippe': 'Patek Philippe',
  'audemars-piguet': 'Audemars Piguet',
  'tag-heuer': 'Tag Heuer',

  // Mama și copilul
  '0-12-luni': '0-12 luni',
  '1-3-ani': '1-3 ani',
  '3-6-ani': '3-6 ani',
  '6-12-ani': '6-12 ani',
  'haine-bebelusi': 'Haine bebeluși',
  'costume-copil': 'Costume copil',
  'pantofi-copil': 'Pantofi copil',
  'cizme-copil': 'Cizme copil',
  'sandalii-copil': 'Sandalii copil',
  'papuci-casa': 'Papuci casă',
  'jucarii-educative': 'Jucării educative',
  'jucarii-electronice': 'Jucării electronice',
  'puzzle': 'Puzzle',
  'masini-jucarii': 'Mașini jucării',
  'jucarii-exterior': 'Jucării exterior',
  'patut': 'Patut',
  'comoda': 'Comodă',
  'dulap-copil': 'Dulap copil',
  'birou-copil': 'Birou copil',
  'pui-sertar': 'Pui sertar',
  'carucior': 'Cărucior',
  'sacosa-copil': 'Sacoșă copil',
  'pat-purtator': 'Pat purtător',
  'ham': 'Ham',
  'accesorii-puericultura': 'Accesorii puericultură',
  'sterilizatoare': 'Sterilizatoare',
  'termometre': 'Termometre',
  'aspiratoare-nas': 'Aspiratoare nas',
  'umidificatoare': 'Umidificatoare',
  'monitoare-bebelus': 'Monitori bebeluș',
  'grupa-0': 'Grupă 0',
  'grupa-0-plus': 'Grupă 0+',
  'grupa-1': 'Grupă 1',
  'grupa-2-3': 'Grupă 2/3',
  'scaun-izofix': 'Scaun Isofix',
  'baza-auto': 'Bază auto',
  'carucior-complet': 'Cărucior complet',
  'carucior-simplu': 'Cărucior simplu',
  'twin': 'Twin',
  'carucior-sport': 'Cărucior sport',
  'accesorii-carucior': 'Accesorii cărucior',
  'biberoane': 'Biberoane',
  'tetine': 'Tetine',
  'incalzitoare': 'Încălzitoare',
  'mameloane': 'Mamelon',
  'tacamuri-copil': 'Tacâmuri copil',

  // Agricultură
  'tractor-mic': 'Tractor mic',
  'tractor-mediu': 'Tractor mediu',
  'tractor-mare': 'Tractor mare',
  'combina-cereale': 'Combina cereale',
  'combina-porumb': 'Combina porumb',
  'accesorii-tractor': 'Accesorii tractor',
  'remorca-platforma': 'Remorcă platformă',
  'remorca-basculanta': 'Remorcă basculantă',
  'remorca-cisterna': 'Remorcă cisternă',
  'pompe': 'Pompe',
  'conducte': 'Conducte',
  'stropitoare': 'Stropitoare',
  'sisteme-pivot': 'Sisteme pivot',
  'gouturare': 'Gouturare',
  'bovine': 'Bovine',
  'ovine': 'Ovine',
  'porcine': 'Porcine',
  'pasarim': 'Păsărim',
  'echide': 'Ecvide',
  'seminte': 'Semințe',
  'furaje': 'Furaje',
  'ingrasaminte': 'Îngrășăminte',
  'protectie-vegetala': 'Protecție vegetală',
  'tratamente': 'Tratamente',

  // Maritime
  'barca-mica': 'Barcă mică',
  'barca-mare': 'Barcă mare',
  'iaht': 'Iaht',
  'velier': 'Velier',
  'skijet': 'Skijet',
  'canot': 'Canot',
  'kayak': 'Kayak',
  'motor-outboard': 'Motor outboard',
  'motor-inboard': 'Motor inboard',
  'motor-electronic': 'Motor electronic',
  'pompe-bord': 'Pompe bord',
  'avion-usoar': 'Avion ușor',
  'ultralight': 'Ultralight',
  'paramotor': 'Paramotor',
  'planor': 'Planor',
  'elicopter-mic': 'Elicopter mic',
  'drone-inspecție': 'Drone inspecție',
  'drone-agriculture': 'Drone agricultură',
  'drone-mapping': 'Drone mapping',
  'drone-transport': 'Drone transport',

  // Business
  'calculatoare': 'Calculatoare',
  'imprimante': 'Imprimante',
  'scanere': 'Scanere',
  'mobilier-birou': 'Mobilier birou',
  'echipamente-prezentare': 'Echipamente prezentare',
  'vitrine': 'Vitrine',
  'rafturi-comerciale': 'Rafturi comerciale',
  'case-incarcare': 'Case încărcare',
  'mese-showroom': 'Mese showroom',
  'scaune-receptie': 'Scaune recepție',
  'laptop-second': 'Laptop second',
  'desktop-second': 'Desktop second',
  'workstation': 'Workstation',
  'server': 'Server',
  'monitoare': 'Monitoare',
  'loturi-mixte': 'Loturi mixte',
  'electronice': 'Electronice',
  'haine': 'Haine',
  'cosmetice': 'Cosmetice',
  'alimente': 'Alimente',
  'materiale': 'Materiale',

  // Materiale
  'ciment': 'Ciment',
  'caramida': 'Cărămidă',
  'beton': 'Beton',
  'otel-constructii': 'Oțel construcții',
  'placi': 'Plăci',
  'blocuri': 'Blocuri',
  'vata-minerala': 'Vată minerală',
  'polistiren': 'Polistiren',
  'polistiren-extrus': 'Polistiren extrus',
  'sticla-spuma': 'Sticlă spumă',
  'termoizolatie-pereti': 'Termoizolație pereți',
  'termoizolatie-acoperis': 'Termoizolație acoperiș',
  'folie-termoizolanta': 'Folie termoizolantă',
  'balamale': 'Balamale',
  'chei': 'Chei',
  'serruri': 'Serruri',
  'unelte-manuale': 'Unelte manuale',
  'unelte-electrice': 'Unelte electrice',
  'echipamente-protectie': 'Echipamente protecție',
  'usi-interior': 'Uși interior',
  'usi-exterior': 'Uși exterior',
  'ferestre-pvc': 'Ferestre PVC',
  'ferestre-aluminiu': 'Ferestre aluminiu',
  'ferestre-lemn': 'Ferestre lemn',
  'tamplarie': 'Tâmplărie',

  // Diverse
  'donatii-speciale': 'Donații speciale',
  'uniformes': 'Uniforme',
  'decoratii': 'Decorații',
  'obiecte-istorice': 'Obiecte istorice',
  'arma-colectie': 'Armă colecție',
  'documente': 'Documente',
  'nft-arta': 'NFT artă',
  'nft-muzica': 'NFT muzică',
  'nft-collectibles': 'NFT collectibles',
  'nft-utility': 'NFT utility',
  'vinuri': 'Vinuri',
  'whisky': 'Whisky',
};

/** Mapare subcategorie (nume afișat) la key pentru Level 3 - ManualAddModalExecutor */
export const SUBCATEGORY_DISPLAY_TO_KEY: Record<string, string> = {
  // Imobiliare
  'Apartamente': 'apartamente',
  'Case și Vile': 'case-vile',
  'Case și vile': 'case-vile',
  'Terenuri': 'terenuri',
  'Terenuri Intravilane': 'terenuri-intravilane',
  'Terenuri Extravilane': 'terenuri-extravilane',
  'Terenuri Agricole': 'terenuri-agricole',
  'Spații Comerciale': 'spatii-comerciale',
  'Hale Industriale': 'hale-industriale',
  'Proprietăți Turistice': 'proprietati-turistice',
  // Autovehicule
  'Autoturisme': 'autoturisme',
  'SUV / 4x4': 'suv-4x4',
  'Motociclete și Scutere': 'motociclete',
  'Camioane': 'camioane',
  'Remorci și Semiremorci': 'remorci',
  'Autorulote / Rulote': 'autorulote',
  'Vehicule Electrice': 'vehicule-electrice',
  'Piese Auto și Accesorii': 'piese-auto',
  'Piese auto și accesorii': 'piese-auto',
  // Utilaje
  'Utilaje Construcții': 'utilaje-constructii',
  'Utilaje construcții': 'utilaje-constructii',
  'Utilaje Agricole': 'utilaje-agricole',
  'Echipamente Forestiere': 'echipamente-forestiere',
  'Generatoare și Compresoare': 'generatoare',
  'Scule Profesionale': 'scule-profesionale',
  'Echipamente Ateliere Auto': 'echipamente-ateliere',
  'Echipamente Electrice / Sudură': 'echipamente-electrice',
  // Artă
  'Picturi': 'picturi',
  'Sculpturi': 'sculpturi',
  'Bijuterii și Ceasuri': 'bijuterii',
  'Bijuterii și ceasuri': 'bijuterii',
  'Obiecte de Colecție': 'obiecte-colectie',
  'Mobilier de Epocă': 'mobilier-epoca',
  'Cărți Rare, Hărți Vechi': 'carti-rare',
  'Fotografie Artistică': 'fotografie-artistica',
  'Licitații Caritabile': 'licitatii-caritabile',
  // Electronice
  'Laptopuri și PC-uri': 'laptopuri-pc',
  'Laptopuri și pc-uri': 'laptopuri-pc',
  'Telefoane Mobile': 'telefoane',
  'Telefoane mobile': 'telefoane',
  'Tablete': 'tablete',
  'TV & Audio': 'tv-audio',
  'Console & Jocuri': 'console-jocuri',
  'Drone & Gadgeturi Smart': 'drone-gadgeturi',
  'Echipamente Foto/Video': 'echipamente-foto',
  // Casă
  'Mobilier Interior': 'mobilier-interior',
  'Mobilier Exterior': 'mobilier-exterior',
  'Echipamente de Grădinărit': 'echipamente-gradinarit',
  'Decorațiuni': 'decoratiuni',
  'Electrocasnice': 'electrocasnice',
  // Modă
  'Haine de Designer': 'haine-designer',
  'Încălțăminte': 'incaltaminte',
  'Genți & Accesorii': 'genti-accesorii',
  'Parfumuri & Cosmetice': 'parfumuri-cosmetice',
  'Ceasuri de Lux': 'ceasuri-lux',
  // Mama și copilul
  'Haine copil': 'haine-copil',
  'Încălțăminte copil': 'incaltaminte-copil',
  'Jucării': 'jucarii',
  'Mobilier copil': 'mobilier-copil',
  'Coșul copilului': 'cosul-copilului',
  'Îngrijire bebeluși': 'ingrijire-bebelusi',
  'Scaune auto copil': 'scaune-auto-copil',
  'Cărucioare': 'carucioare',
  'Hranire copil': 'hranire-copil',
  // Agricultură
  'Tractoare, Combine': 'tractoare-combine',
  'Remorci Agricole': 'remorci-agricole',
  'Echipamente de Irigații': 'echipamente-irigatii',
  'Animale': 'animale',
  'Semințe, Furaje, Îngrășăminte': 'seminte-furaje',
  // Maritime
  'Bărci, Iahturi, Skijeturi': 'barci-iahturi',
  'Motoare Marine': 'motoare-marine',
  'Avioane Mici / Ultraleușoare': 'avioane',
  'Dronuri Industriale': 'drone-industriale',
  // Business
  'Echipamente de Birou': 'echipamente-birou',
  'Mobilier Comercial': 'mobilier-comercial',
  'Calculatoare Second-Hand': 'calculatoare-second',
  'Licitații Lichidări Firme': 'lichidari-firme',
  'Loturi Stocuri Produse': 'loturi-stocuri',
  // Materiale
  'Ciment, Cărămidă, Oțel': 'ciment-caramida',
  'Materiale Izolație': 'materiale-izolatie',
  'Materiale izolație': 'materiale-izolatie',
  'Feronerie, Unelte': 'feronerie-unelte',
  'Uși, Ferestre, Tâmplărie': 'usi-ferestre',
  // Diverse (Licitații Caritabile share cu Artă -> licitatii-caritabile)
  'Obiecte Militare / Istorice': 'militare-istorice',
  'NFT / Artă Digitală': 'nft-arta-digitala',
  'Colecții Private': 'colectii-private',
  'Bunuri Confiscate / Execuții': 'bunuri-confiscate',
  // Executări (categorii comune Executori + Insolvență)
  'Imobiliare': 'exec-imobiliare',
  'Autovehicule': 'exec-autovehicule',
  'Industrial': 'exec-industrial',
  'Afaceri': 'exec-afaceri',
  'Office': 'exec-office',
  'Altele': 'exec-altele',
};
