/**
 * Generate empty/minimal dictionary scaffolds for ALL categories/subcategories.
 * Reads RO_CATEGORIES from lib/data/ro-categories.ts and creates:
 *   lib/categorization/dictionaries/ro/{categorySlug}.ts
 *   lib/categorization/dictionaries/ro/index.ts (registry)
 *
 * Run: npx tsx scripts/generate-categorization-dictionaries.ts
 */

import * as fs from "fs";
import * as path from "path";
import { RO_CATEGORIES } from "../lib/data/ro-categories";

const DICT_DIR = path.join(process.cwd(), "lib", "categorization", "dictionaries", "ro");

function slugToVar(slug: string): string {
  return slug.replace(/-/g, "_");
}

function main() {
  if (!fs.existsSync(DICT_DIR)) {
    fs.mkdirSync(DICT_DIR, { recursive: true });
  }

  const categories = Object.keys(RO_CATEGORIES).filter((k) => k !== "all");
  const exports: string[] = [];
  const allEntries: string[] = [];

  for (const catSlug of categories) {
    const entry = RO_CATEGORIES[catSlug];
    const subs = entry?.subcategories ?? [];
    const varName = slugToVar(catSlug);
    const fileName = `${catSlug}.ts`;

    const entries: string[] = [];
    for (const subSlug of subs) {
      entries.push(`  {
    target: { categorySlug: "${catSlug}", subcategorySlug: "${subSlug}" },
    includeAny: [],
    confidence: 0.75,
    reason: "${catSlug}/${subSlug} placeholder",
  }`);
    }

    const content = `/**
 * Dictionary entries for category: ${catSlug}
 * Generated by scripts/generate-categorization-dictionaries.ts
 */

import type { DictionaryEntry } from "../types";

export const ${varName}Entries: DictionaryEntry[] = [
${entries.length ? entries.join(",\n") : "  // Add entries with includeAny, includeAll, excludeAny, attributes"}
];
`;
    fs.writeFileSync(path.join(DICT_DIR, fileName), content, "utf8");

    exports.push(`export { ${varName}Entries } from "./${catSlug}";`);
    allEntries.push(`...${varName}Entries`);
  }

  const indexContent = `/**
 * Registry of all dictionary entries (all categories/subcategories).
 * Generated by scripts/generate-categorization-dictionaries.ts
 */

${exports.join("\n")}

import type { DictionaryEntry } from "../types";

export const ALL_DICTIONARY_ENTRIES: DictionaryEntry[] = [
  ${allEntries.join(",\n  ")},
];
`;
  fs.writeFileSync(path.join(DICT_DIR, "index.ts"), indexContent, "utf8");

  console.log(`Generated ${categories.length} category files + index in ${DICT_DIR}`);
}

main();
