-- Hotfix indexes for slow PostgREST product queries observed on 2026-05-01.
-- Focus: ILIKE filters (city/county/brand/title) + category/subcategory predicates
-- used in both data page and count queries.

create extension if not exists pg_trgm;

-- Raw-column trigram indexes to match `column ilike $1` generated by PostgREST.
-- Existing expression indexes on lower(...) may not always be chosen for this SQL shape.
create index if not exists products_city_trgm_hot_idx
  on public.products using gin (city extensions.gin_trgm_ops)
  where city is not null
    and city <> ''
    and status <> 'deleted';

create index if not exists products_county_trgm_hot_idx
  on public.products using gin (county extensions.gin_trgm_ops)
  where county is not null
    and county <> ''
    and status <> 'deleted';

create index if not exists products_brand_trgm_hot_idx
  on public.products using gin (brand extensions.gin_trgm_ops)
  where brand is not null
    and brand <> ''
    and status <> 'deleted';

create index if not exists products_title_trgm_hot_idx
  on public.products using gin (title extensions.gin_trgm_ops)
  where title is not null
    and title <> ''
    and status <> 'deleted';

-- Fast path for common approved listings by category + subcategory sorted by newest.
create index if not exists products_approved_cat_subcat_created_hot_idx
  on public.products (category, subcategory, created_at desc, id desc)
  where status <> 'deleted'
    and coalesce(approval_status, 'approved') = 'approved'
    and category is not null
    and category <> ''
    and subcategory is not null
    and subcategory <> '';

-- Same path when filter can match category_level_3 instead of subcategory.
create index if not exists products_approved_cat_level3_created_hot_idx
  on public.products (category, category_level_3, created_at desc, id desc)
  where status <> 'deleted'
    and coalesce(approval_status, 'approved') = 'approved'
    and category is not null
    and category <> ''
    and category_level_3 is not null
    and category_level_3 <> '';

-- Broad fallback for newest approved feed pages used with LIMIT/OFFSET.
create index if not exists products_approved_status_created_hot_idx
  on public.products (status, created_at desc, id desc)
  where status <> 'deleted'
    and coalesce(approval_status, 'approved') = 'approved';
